namespace Megabonk.BonkWithFriends.Net;

public enum Op : byte
{
	HostWelcome = 1,
	ClientIntroduce = 2,
	PlayerJoined = 3,
	PlayerLeft = 4,
	SeedSync = 5,
	PlayerState = 6,
	Chat = 7,
	LoadLevel = 8,
	Ready = 9,
	PlayerDamaged = 10,
	PlayerHealed = 11,
	PlayerDied = 12,
	PlayerMovement = 13,
	PlayerMovementRelay = 16,
	XpGained = 14,
	LevelUp = 15,
	PickupCollected = 20,
	PickupSpawned = 21,
	PickupDespawned = 22,
	EnemySpawned = 30,
	EnemyDamaged = 31,
	EnemyDied = 32,
	EnemyStateBatch = 33,
	WeaponAdded = 40,
	WeaponAttackStarted = 41,
	WeaponProjectileSpawned = 42,
	WeaponProjectileHit = 43,
	AnimationState = 45,
	GameStarted = 50,
	GameOver = 51,
	TimelineEvent = 52,
	WaveCue = 53,
	WaveFinalCue = 54,
	BossSpawnSync = 55,
	BossDied = 56,
	WavesStopped = 57,
	InteractableSpawnBatch = 60,
	InteractableUsed = 61
}
